sudo: required
services:
- docker
script:
- docker build --tag "$IMAGE_NAME" .
after_script:
- docker images
before_deploy:
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_BUILD_NUMBER}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TRAVIS_BUILD_NUMBER}"
  on:
    branch: master
env:
  global:
  - IMAGE_NAME=npiper/openjdk8-graphviz
  - secure: YlTsQ59V3YbnRAmDVGexuGTH0kAfxLb4o0ue3toGKDiCbWspYRdHgf362Hg5SUili+UFvjx60+MEfBR/2Ntr9NZArC+Z/jl9Aj/y5DYIPfHJVOgXdJHyUTw3Z5WNSYNi0bg9ysVjbZPpLQjMrSf9lwl2yBo37r2ufzifI5b6YFhWEzaeOaOd8ehCQSKIdVst5jt53h/CUv0/HSiVfBnWJUjJugZrCaEp89WVyoAOvJsT4bP8Ji1H0bJyVJQ471uJ7LU4XlBLlzNvT+JeMq14iUq2CG8CrKQ+XkLwmtiGJ9PPoH/pQMCYb84urm7hNYJTwBYBx8vhP6PYv+mn6TcmG0QCFDAUW+lPJi87A6seMWuPT4RgKhkRFUMAdotVDwTvhfQ82naTntpMULCr7Kda0sSqULn1zNf97iSIKJbKEUGq/wsoBmth5pK1J3JeiRA5O57T8NkV76r8rWv9A9Hnt3DPMBfALzB20AnGXnum55wDAKqCv4g7np/JEwTviwwC7MbLO+iChYde6FC/JgIKYo50lRqGWu2/Vx5NVy3LpB42USnfesw59Oc+fuThiAQTOpM8OzPXmC89cVteSm+4ZSxIuuEUpn/SdnRr8KFkg9/BvtOElP51TPHBYH8v2iJ/Xv98ZRUmLy/VmqFanEDSspRc+eiyceGfvhsDD0U3miY=
  - secure: v90Wn1lED5bcqbzOyohXD8UO5GDHbmDxt2q1fIWXSdX/BJE6gwrYP+uCXu7d0xTH+pnbntgGuQqwKtoR6g/erHDJFEODyxZUkBlHkhfVA7Nuv8bfc+U2LpczI9uKhAA4aOyDdeek4c49gyEtbU6u9nFnGlBgbVhvCawYbspoT8Pp8116ZPJR2ZUb/66KL8LuTjlF01d0dYXC8wrASDiP/N/WfzVlInrx1dDoaitORAj9MDEh4t6e6UD/9C7MTU3V7znNQv5lqWmKfMqndSY/sjUdHSBzsxTOpjxsXUtjJwP+HeRcaPo5mquVs5120R4kC1PJxDPaTwZ7+p6gkIAtgQIc1hzG7nGwAoWuMbrgaNLYqZoXcjwDYgMNnrDP5L1qk2MAQlnmM/US88tKfW5DONARokwqr170jF4oCaGbkLBFiEascadTUK62vBtMVPza+4KvOMMLK9ZiG/3ZzQmOFUa8fLceeg+KszFE9J/S1sCqrslbmLejjBB/oWnIHF0lFjNEVmbj9y7d1nZ4CFQf0W0UTamdAefHvhaGGSd5KvKAm5ZM1CMw/+YuLrqWtlJyNmVqwpHnUASptf1bwFk/lk2pqcZsT4dl/p9KVYIof+pXwahk0bCiTuzbMrsZMdb3PdjOc3qS73PRbl+wmL7HJVEJ0BR5nLSaGx0bNeGNQH8=
